"""add_transport_abuse_snooze_audit_soft_delete

Revision ID: 70ba141d3be2
Revises: de8700ddb241
Create Date: 2026-02-24 03:19:49.585961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ba141d3be2'
down_revision: Union[str, Sequence[str], None] = 'de8700ddb241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=100), nullable=False),
    sa.Column('last_broadcast_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_broadcasts_route_id'), 'transport_broadcasts', ['route_id'], unique=False)
    op.create_index(op.f('ix_transport_broadcasts_school_id'), 'transport_broadcasts', ['school_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.add_column('tickets', sa.Column('known_issue', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tickets', sa.Column('abuse_flagged', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tickets', sa.Column('abuse_flagged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('abuse_flagged_by_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('escalation_snoozed_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['abuse_flagged_by_id'], ['id'])
    op.add_column('users', sa.Column('restricted_to_admin_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ticket_creation_blocked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ticket_creation_blocked_until')
    op.drop_column('users', 'restricted_to_admin_until')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'deleted_at')
    op.drop_column('tickets', 'escalation_snoozed_until')
    op.drop_column('tickets', 'abuse_flagged_by_id')
    op.drop_column('tickets', 'abuse_flagged_at')
    op.drop_column('tickets', 'abuse_flagged')
    op.drop_column('tickets', 'known_issue')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_transport_broadcasts_school_id'), table_name='transport_broadcasts')
    op.drop_index(op.f('ix_transport_broadcasts_route_id'), table_name='transport_broadcasts')
    op.drop_table('transport_broadcasts')
    # ### end Alembic commands ###
