"""add_satisfied_at_and_ticket_reopens

Revision ID: a498fbfe4ff0
Revises: 768234247bbe
Create Date: 2026-02-24 03:05:08.224264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a498fbfe4ff0'
down_revision: Union[str, Sequence[str], None] = '768234247bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reopens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_reopens_requested_by_id'), 'ticket_reopens', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_ticket_reopens_ticket_id'), 'ticket_reopens', ['ticket_id'], unique=False)
    op.add_column('tickets', sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'satisfied_at')
    op.drop_index(op.f('ix_ticket_reopens_ticket_id'), table_name='ticket_reopens')
    op.drop_index(op.f('ix_ticket_reopens_requested_by_id'), table_name='ticket_reopens')
    op.drop_table('ticket_reopens')
    # ### end Alembic commands ###
